### PR TITLE
Clean up compiler directives. Close #43

### LINKED ISSUE #43: Clean up compiler directives
Clean up compiler directives using {$IF CompilerVersion >= XX} and more meaningful compiler directives names.
No more {$IFDEF VERXYZ}

### PR DESCRIPTION
**Pull request by fabriciocolombo**
Tested with Delphi 7, 2007, 2010, XE e XE2.

### CODE REVIEW

**Comment by fabioxgn** [comment]
:+1: Tested with XE7, works fine too.

**Comment by fabriciocolombo** [comment]
Thanks for the info @fabioxgn.
Can you review this PR @RobertoSchneiders?

**Comment by RobertoSchneiders** [comment]
Looks great @fabriciocolombo. :shipit:

**Comment by fabriciocolombo** [comment]
Then I'll do the merge.

**Pull request merged**
