### PR TITLE
Verify cert. Bug fixes. New events. WinInet and WinHTTP connection lost support.

### PR DESCRIPTION
**Pull request by thomaserlang**
Anyone knows how to get Indy to validate certificates against the default Windows CA store?

### CODE REVIEW

**Comment by RobertoSchneiders** [comment]
:+1: 

About the Indy certificate validation, AFAIK OpenSSL doesn't uses the Windows CA, so, you will have to implement a custom `onVerifyPeer` that does that.

**Comment by fabriciocolombo** [comment]
You're awesome @thomaserlang. Thank you so much.

**Comment by thomaserlang** [comment]
Done and done.

**Comment by fabriciocolombo** [comment]
Thank you.

**Pull request merged**
