### PR TITLE
Added better ISO 8601 and variant handling for superobject

### PR DESCRIPTION
**Pull request by thomaserlang**

### CODE REVIEW

**Comment by RobertoSchneiders** [comment]
@thomaserlang You commited a newer version of superobject or you really changed it?

**Comment by thomaserlang** [comment]
I changed it.

**Comment by RobertoSchneiders** [comment]
:+1: @thomaserlang For me it is ok. 

Have any reason to not merge it?

**Comment by thomaserlang** [comment]
No, I believe it's better than what was there before.

**Pull request merged**
